<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <RootNamespace>Taazaa.Shared.DevKit.Framework.Search</RootNamespace>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <FileVersion>0.1.0</FileVersion>
        <LangVersion>latest</LangVersion>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>0.1.0</Version>
        <Title>Taazaa.Shared.DevKit.Framework.Search</Title>
        <Authors>Taazaa</Authors>
        <RepositoryUrl>https://bitbucket.org/taazaainc/taazaa.shared.devkit.framework</RepositoryUrl>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageId>Taazaa.Shared.DevKit.Framework.Search</PackageId>
        <Description>Sech framework</Description>
        <Copyright>Copyright 2023 Taazaa</Copyright>
        <PackageProjectUrl>https://bitbucket.org/taazaainc/taazaa.shared.devkit.framework/src/main/src/libraries/Search</PackageProjectUrl>
        <PackageTags>queryable;search</PackageTags>
        <AssemblyName>Taazaa.Shared.DevKit.Framework.Search</AssemblyName>
        <RuntimeIdentifiers>win-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <IsPackable>true</IsPackable>
        <PackageReadMeFile>README.md</PackageReadMeFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DocumentationFile>bin\Debug\Taazaa.Shared.DevKit.Framework.Search.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2023.2.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="3.3.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SonarAnalyzer.CSharp" Version="9.10.0.77988">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
        <PackageReference Include="System.Text.Json" Version="7.0.3" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="PublicAPI.Shipped.txt" />
        <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
